//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerInIkebana
    {
        public int Id { get; set; }
        public int IdFlower { get; set; }
        public int IdIkebana { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Ikebana Ikebana { get; set; }
    }
}
