//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowerDBEntities : DbContext
    {
        public FlowerDBEntities()
            : base("name=FlowerDBEntities")
        {
        }
        private static FlowerDBEntities _context;
        public static FlowerDBEntities GetContext()
        {
            if (_context == null)
                _context = new FlowerDBEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flower> Flower { get; set; }
        public virtual DbSet<FlowerInIkebana> FlowerInIkebana { get; set; }
        public virtual DbSet<Ikebana> Ikebana { get; set; }
        public virtual DbSet<IkebanaInUser> IkebanaInUser { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
